import Head from 'next/head'
import { Inter, M_PLUS_1 } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import data from '../data/employee.json'
import Employ from '../components/Employ'
import { useState } from 'react'
import Image from 'next/image'
import Link from 'next/link'

export default function About() {
  console.log(data);
  const [information, setInformation] = useState([...data])

  return (
    <>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.description}>
          <p>
            <Link href="/pages/index.js">Home Page</Link>

          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{' '}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <h1>Meet Our Staff</h1>


        </div>

        <div className={styles.grid}>
          <b>Product</b>
          {information && information.map((info, index) => {
            if (info.name === "Jeffery Williams") {
              return (
                <Employ key={index} name={info.name} started={info.started} department={info.department} colour="#000356" font="12px" />
              )

            }
          })}
                {information && information.map((info, index) => {
            if (info.name === "Sarah Peterson") {
              return (
                <Employ key={index} name={info.name} started={info.started} department={info.department} colour="#000037" font="12px" />
              )

            }
          })}
               {information && information.map((info, index) => {
            if (info.department === "Product Research") {
              return (
                <Employ key={index} name={info.name} started={info.started} department={info.department} colour="#000022" font="12px" />
              )

            }
          })}
          <b>Design</b>
          {information && information.map((info, index) => {
            if (info.department === "UX Design") {
              return (
                <Employ key={index}  name={info.name}
                started={info.started} department={info.department} colour="purple" font="12px" />
              )

            }
          })}
               {information && information.map((info, index) => {
            if (info.department === "UI Design") {
              return (
                <Employ key={index}  name={info.name}
                started={info.started} department={info.department} colour="blue" font="12px" />
              )

            }
          })}
        </div>
      </main>
    </>
  )


}